return {
	"folke/which-key.nvim",
	"ThePrimeagen/vim-be-good",
	{ "folke/neoconf.nvim", cmd = "Neoconf" },
	"startup-nvim/startup.nvim",
	"nvim-telescope/telescope-media-files.nvim",
	"gbprod/yanky.nvim",
	{ "echasnovski/mini.nvim", version = false },
	"folke/lsp-colors.nvim",
	"folke/neodev.nvim",
	"gelguy/wilder.nvim",
	{ "github/copilot.vim", lazy = false },
	"bluz71/vim-nightfly-guicolors",
	"nvim-lualine/lualine.nvim",
	"junegunn/fzf.vim",
	{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
	{ "nvim-telescope/telescope.nvim", branch = "0.1.x" },
	"ThePrimeagen/harpoon",
	"hrsh7th/nvim-cmp",
	"sam4llis/nvim-tundra",
	"rebelot/kanagawa.nvim",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-path",
	"L3MON4D3/LuaSnip",
	"saadparwaiz1/cmp_luasnip",
	"rafamadriz/friendly-snippets",
	"fgheng/winbar.nvim",
	"williamboman/mason.nvim",
	"williamboman/mason-lspconfig.nvim",
	"nvimdev/lspsaga.nvim",
	"neovim/nvim-lspconfig",
	"hrsh7th/cmp-nvim-lsp",
	"jose-elias-alvarez/typescript.nvim",
	"onsails/lspkind.nvim",
	"jose-elias-alvarez/null-ls.nvim",
	"jayp0521/mason-null-ls.nvim",
	{
		"nvim-treesitter/nvim-treesitter",
		run = function()
			local ts_update = require("nvim-treesitter.install").update({ with_sync = true })
			ts_update()
		end,
	},
	"windwp/nvim-autopairs",
	{ "windwp/nvim-ts-autotag", after = "nvim-treesitter" },
	"lewis6991/gitsigns.nvim",
	"Everblush/everblush.nvim",
	"rhysd/clever-f.vim",
	"frazrepo/vim-rainbow",
	{
		"rebelot/heirline.nvim",
		config = function()
			require("heirline").setup({})
		end,
	},
	"rcarriga/nvim-notify",
	"yorik1984/lualine-theme.nvim",
	"nvim-tree/nvim-web-devicons",
	"tyru/open-browser.vim",
	"aklt/plantuml-syntax",
	"weirongxu/plantuml-previewer.vim",
	"rockerBOO/boo-colorscheme-nvim",
	"heraldofsolace/nisha-vim",
	"rktjmp/lush.nvim",
	"tersetears/maani.nvim",
	"aswathkk/DarkScene.vim",
	"numToStr/FTerm.nvim",
	"ThePrimeagen/git-worktree.nvim",
	"rmagatti/auto-session",
	"rmagatti/session-lens",
	"bluz71/vim-nightfly-colors",
	"bluz71/vim-moonfly-colors",
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	"numToStr/Comment.nvim",
	"lukas-reineke/indent-blankline.nvim",
	"vim-scripts/DoxygenToolkit.vim",
	"EdenEast/nightfox.nvim",
	"nvim-lua/plenary.nvim",
	"mfussenegger/nvim-dap",
	"yonlu/omni.vim",
	"xiyaowong/transparent.nvim",
	"averms/black-nvim",
	"tiagovla/tokyodark.nvim",
	"Nero-F/vim-tek-header",
	{ "eddyekofo94/gruvbox-flat.nvim" },
	{ "AlexvZyl/nordic.nvim" },
	"shaunsingh/nord.nvim",
	"projekt0n/github-nvim-theme",
	"simrat39/rust-tools.nvim",
	{
		"glepnir/dashboard-nvim",
		dependencies = { { "nvim-tree/nvim-web-devicons" } },
	},
	{ "goolord/alpha-nvim", dependencies = { { "nvim-tree/nvim-web-devicons" } } },
	{ "dawsers/telescope-floaterm.nvim" },
}
