-- require("plugins.dashboard")
require("plugins.copilot")
require("plugins.harpoon")
require("plugins.indent_blankline")
require("plugins.comments")
require("plugins.lualine")
require("plugins.illuminate")
require("plugins.autopairs")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.treesitter")
require("plugins.lsp")
