-- require("plugins.dashboard")
require("plugins.wilder")
require("plugins.catppucin")
require("plugins.alpha")
require("plugins.mini")
require("plugins.lsp-colors")
require("plugins.yank")
require("plugins.kanagawa")
require("plugins.copilot")
require("plugins.harpoon")
require("plugins.indent_blankline")
require("plugins.comments")
require("plugins.transparent")
require("plugins.github_theme")
require("plugins.lualine")
require("plugins.illuminate")
require("plugins.autopairs")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.treesitter")
-- Need to install plugin flutter before using this
-- require("plugins.flutter")
require("plugins.lsp")
